[[variables]]
test = 1
radius = 0.7

[[sphere]]
name = "ball1"
radius = "var radius"
position = [1.0, -0.5, 10.0]

[[joint]]
joint_type = "ball"
name = "ball_joint_2"
parent = "ball1"
child = "ball2"

[[sphere]]
name = "ball2"
radius = "var radius"
color = [1.0, 0.0, 0.0]
position = [1.0, 0.5, 10.0]

[[box]]
name = "box1"
sides = [1, 1, 1]
color = ["var test", "var test", "var test"]
position = [-1.0, 0.5 , 6.0]

[[joint]]
name = "ball_joint_1"
joint_type = "ball"
parent = "box1"
child = "asdf"

[[box]]
name = "asdf"
sides = [1, 1, 1]
position = [-1.0, -0.5 , 5.0]

[[box]]
name = "box3"
sides = [1, 1, 1]
position = [1.0, 0.5 , 6.0]

[[joint]]
joint_type = "ball"
name = "ball_joint_3"
parent = "box3"
child = "box4"

[[box]]
name = "box4"
sides = [1, 1, 1]
color = [0, 1, 1]
position = [1.0, -0.5 , 5.0]

[[box]]
name = "fdafa"
sides = [5, 5, 5]
color = [1, 0, 0]
position = [1.0, -0.5 , 20.0]