[[constants]]
test = [-1.0, 0.5 , 6.0]
radius = 1.0
box_color = [1, 1, 0]

[[non_colliding_groups]]
group1 = ["box1", "asdf", "big_box"]
group2 = ["box3", "box4", "big_box"]

[[sphere]]
name = "ball1"
radius = "$radius"
position = [1.0, -0.5, 10.0]

[[joint]]
joint_type = "ball"
name = "ball_joint_2"
parent = "ball1"
child = "ball2"

[[sphere]]
name = "ball2"
radius = "$radius"
color = "$box_color"
position = [1.0, 0.5, 10.0]

[[box]]
name = "box1"
sides = [1, 1, 1]
color = "$box_color"
position = "$test"

[[joint]]
name = "ball_joint_1"
joint_type = "ball"
parent = "box1"
child = "asdf"

[[box]]
name = "asdf"
sides = [1, 1, 1]
position = [-1.0, -0.5 , 5.0]

[[box]]
name = "box3"
sides = [1, 1, 1]
position = [1.0, 0.5 , 6.0]

[[joint]]
joint_type = "ball"
name = "ball_joint_3"
parent = "box3"
child = "box4"

[[box]]
name = "box4"
sides = [1, 1, 1]
color = "$box_color"
position = [1.0, -0.5 , 5.0]

[[box]]
name = "big_box"
sides = [5, 5, 5]
color = [1, 0, 0]
position = [1.0, -0.5 , 20.0]