[[sphere]]
name = "ball1"
radius = 0.5
color = [1.0, 0.0, 0.0]
position = [0.2, 0.0, 5.0]

[[sphere]]
name = "ball2"
radius = 0.5
color = [1.0, 1.0, 0.0]
position = [0.2, 0.0, 9.0]

[[box]]
name = "box1"
sides = [1, 1, 1]
position = [0.0, 0.0 , 7.0]

[[box]]
name = "box2"
sides = [1, 1, 1]
position = [0.0, 0.0 , 12.0]