[[model]]
name = "car"

[[constants]]
wheel_radius = 0.5

#Macro Creation
[[macro.wheel_and_axis]]
parent_name = ""
my_name = ""
relative_child_position = []
relative_joint_position = []
joint_axis = []

    [[macro.wheel_and_axis.sphere]]
    name = "$my_name"
    radius = "$wheel_radius"
    relative_position = "$relative_child_position"

    [[macro.wheel_and_axis.revolute]]
    name = "$my_name"
    axis = "$joint_axis"
    relative_position = "$relative_joint_position"
    parent = "$parent_name"
    child = "$my_name"

[[box]]
name = "body"
sides = [2.0, 1.0, 0.5]
position = [0, 0, 0]

[[wheel_and_axis]]
parent_name = "body"
my_name = "wheel1"
relative_child_position = [1.0, 1.0, 0.0]
relative_joint_position = [1, 0, 0]
joint_axis = [0, 1, 0]

[[wheel_and_axis]]
parent_name = "body"
my_name = "wheel2"
relative_child_position = [1.0, -1.0, 0.0]
relative_joint_position = [1, 0, 0]
joint_axis = [0, 1, 0]

[[wheel_and_axis]]
parent_name = "body"
my_name = "wheel3"
relative_child_position = [-1.0, -1.0, 0.0]
relative_joint_position = [-1, 0, 0]
joint_axis = [0, 1, 0]

[[wheel_and_axis]]
parent_name = "body"
my_name = "wheel4"
relative_child_position = [-1.0, 1.0, 0.0]
relative_joint_position = [-1, 0, 0]
joint_axis = [0, 1, 0]