[[constants]]
position = [1.0, 0.5 , 6.0]
radius = 1.0
box_color = [1, 1, 0]

## macro definition
[[macro.box_to_box]]
color = ""
position = [0, 0, 10]
name = "no_name"
joint_name = "joint_name"
child_name = "child_name"

    [[macro.box_to_box.box]]
    name = "$name"
    sides = [1, 1, 1]
    color = "$color"
    position = "$position"

    [[macro.box_to_box.ball_and_socket]]
    name = "$joint_name"
    parent = "$name"
    child = "$child_name"
    relative_position = [0.0, 0.5, 0.0]

    [[macro.box_to_box.box]]
    name = "$child_name"
    sides = [1, 1, 1]
    color = "$box_color"
    relative_position = [0.0, 1.0, 0.0]

## macro definition
[[macro.sphere_to_sphere]]
color = ""
position = [0, 0, 10]
name = "no_name"
joint_name = "joint_name"
child_name = "child_name"

    [[macro.sphere_to_sphere.sphere]]
    name = "$name"
    radius = 0.5
    color = "$color"
    position = "$position"

    [[macro.sphere_to_sphere.ball_and_socket]]
    name = "$joint_name"
    parent = "$name"
    child = "$child_name"
    relative_position = [0.0, 0.5, 0.0]

    [[macro.sphere_to_sphere.sphere]]
    name = "$child_name"
    radius = 0.5
    color = "$box_color"
    relative_position = [0.0, 1.0, 0.0]

## macro definition
[[macro.attach_sphere]]
parent_name = ""
my_name = ""
joint_name = ""

    [[macro.attach_sphere.ball_and_socket]]
    name = "$joint_name"
    parent = "$parent_name"
    child = "$my_name"
    relative_position = [0.0, 0.5, 0.0]

    [[macro.attach_sphere.sphere]]
    name = "$my_name"
    radius = 0.5
    color = "$box_color"
    relative_position = [0.0, 1.0, 0.0]

#macro usage
[[box_to_box]]
color = [1, 0, 0]
position = [0, 0, 5]
name = "qwer"
joint_name = "wert"
child_name = "erty"

[[box_to_box]]
color = [0, 1, 0]
position = [0, 0, 9]
name = "rtyu"
joint_name = "tyui"
child_name = "yuio"

[[sphere_to_sphere]]
color = [0, 0, 1]
position = [0, 0, 11]
name = "zxcfv"
joint_name = "xcvb"
child_name = "cvbn"

[[attach_sphere]]
parent_name = "cvbn"
my_name = "jgkh"
joint_name = "ohdirs"

[[attach_sphere]]
parent_name = "jgkh"
my_name = "iuhdh"
joint_name = "poiasd"

[[attach_sphere]]
parent_name = "erty"
my_name = "haegd"
joint_name = "uinfg"